### ISSUE TITLE
TSC计时在超频服务器上的问题

### ISSUE THREAD

**Issue by scorpiostudio** [MengRao/tscns#10]
请教一下，在超频机器上计算出的CPU主频不对呢，比如CPU主频3.0GHZ，超频到5.0GHZ，但计时器计算得到的CPU当前主频仍然是3.0GHZ，是TSC计时有什么问题么？CPU支持invariant tsc。
[xtrader@XXXX ~]$ dmesg | grep "tsc: Refined TSC clocksource calibration"
[    1.851706] tsc: Refined TSC clocksource calibration: 3000.001 MHz

**Comment by scorpiostudio** [comment]
[xtrader@XXXX ~]$ ./timer
init tsc_ghz: 3.00000194999074
rdsys_latency: 12.7522477522478, rdtsc_latency: 5.08224775224775, rdns_latency: 5.67424775224775, tmp: 9177272454853256280
calibrate_latency: 67, tsc_ghz: 3.00000194999074, b2c: 61, c2d: 6, err: 0, rdsysns_latency: 62
calibrate_latency: 11, tsc_ghz: 3.00000194999074, b2c: 154, c2d: -98, err: -98, rdsysns_latency: 51
calibrate_latency: 12, tsc_ghz: 3.00000194999074, b2c: 258, c2d: -213, err: -213, rdsysns_latency: 40
calibrate_latency: 11, tsc_ghz: 3.00000194999074, b2c: 386, c2d: -332, err: -332, rdsysns_latency: 49
calibrate_latency: 13, tsc_ghz: 3.00000194999074, b2c: 490, c2d: -451, err: -451, rdsysns_latency: 34
calibrate_latency: 12, tsc_ghz: 3.00000194999074, b2c: 608, c2d: -567, err: -567, rdsysns_latency: 36
calibrate_latency: 181, tsc_ghz: 3.00000054699048, b2c: 743, c2d: -692, err: -692, rdsysns_latency: 46
calibrate_latency: 12, tsc_ghz: 3.00000054699048, b2c: 615, c2d: -565, err: -565, rdsysns_latency: 45
calibrate_latency: 11, tsc_ghz: 3.00000054699048, b2c: 491, c2d: -449, err: -449, rdsysns_latency: 37
calibrate_latency: 12, tsc_ghz: 3.00000054699048, b2c: 383, c2d: -332, err: -332, rdsysns_latency: 46
calibrate_latency: 12, tsc_ghz: 3.00000054699048, b2c: 255, c2d: -215, err: -215, rdsysns_latency: 35
calibrate_latency: 12, tsc_ghz: 3.00000054699048, b2c: 144, c2d: -94, err: -94, rdsysns_latency: 45
calibrate_latency: 209, tsc_ghz: 3.00000124999077, b2c: 17, c2d: 12, err: 0, rdsysns_latency: 24
calibrate_latency: 12, tsc_ghz: 3.00000124999077, b2c: 27, c2d: 21, err: 0, rdsysns_latency: 43
calibrate_latency: 5, tsc_ghz: 3.00000124999077, b2c: 21, c2d: 20, err: 0, rdsysns_latency: 36
calibrate_latency: 5, tsc_ghz: 3.00000124999077, b2c: 33, c2d: 21, err: 0, rdsysns_latency: 49
calibrate_latency: 5, tsc_ghz: 3.00000124999077, b2c: 15, c2d: 21, err: 0, rdsysns_latency: 31
calibrate_latency: 5, tsc_ghz: 3.00000124999077, b2c: 14, c2d: 12, err: 0, rdsysns_latency: 21
calibrate_latency: 120, tsc_ghz: 3.00000125899078, b2c: 15, c2d: 13, err: 0, rdsysns_latency: 23
calibrate_latency: 5, tsc_ghz: 3.00000125899078, b2c: 31, c2d: 20, err: 0, rdsysns_latency: 46
calibrate_latency: 5, tsc_ghz: 3.00000125899078, b2c: 31, c2d: 20, err: 0, rdsysns_latency: 46
calibrate_latency: 6, tsc_ghz: 3.00000125899078, b2c: 32, c2d: 20, err: 0, rdsysns_latency: 47


[xtrader@XXX ~]$ sudo lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                18
On-line CPU(s) list:   0-17
Thread(s) per core:    1
Core(s) per socket:    18
Socket(s):             1
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 85
Model name:            Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
Stepping:              7
CPU MHz:               4999.877
CPU max MHz:           5000.0000
CPU min MHz:           1200.0000

**Comment by ktprime** [comment]
服务器提供稳定的TSC。你说的频率不是一个层次问题，CPU超频运行的频率和系统TSC计算时钟频率不是一个东西

**Comment by MengRao** [comment]
tsc频率一般是cpu的基础频率，不会随超频而改变。
