### ISSUE TITLE
Concurrency safe?

### ISSUE THREAD

**Issue by DevashishX** [MengRao/tscns#13]
Hi ! I wanted to know if this library was safe to use in a concurrent environment. I have multiple applications running which send messages to each other, so I wanted to know if this library could be used to calculate time taken by each thread to finish a task after receiving some data from another thread. also would it possible to use tscns for calculating startup and shutdown time for the whole application (including all the threads) ?

**Comment by MengRao** [comment]
Yes, tscns is thread safe for reading ns or tsc, but calibrate() should only be called in one thread.
