### ISSUE TITLE
关于sleep影响计时准确性的问题

### ISSUE THREAD

**Issue by zanjun1024** [MengRao/tscns#2]
注释掉 std::this_thread::sleep_for(std::chrono::seconds(1)); 
结果完全不一样，我的机器上（gcc 4.5.8, centos 7.4）rdsysns_latency基本在35ns左右，偶尔也会彪到100+
看上去调用频率影响了函数执行时间？

**Comment by MengRao** [comment]
是的，clock_gettime的数据会被kernel以一定频率更新，如果更新后clock_gettime延迟会高一些，如果没更新会比较快。
