### ISSUE TITLE
Need mfence after builtin_ia32_rtscp

### ISSUE THREAD

**Issue by liushiqi9** [MengRao/tscns#4]
According to [intel_doc](https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/ia-32-ia-64-benchmark-code-execution-paper.pdf)
and  [rdscp](https://www.felixcloutier.com/x86/rdtscp), need to call mfence after builtin_ia32——rtscp incase of cpu reordering.
Using rtsc without cpuid is very bad, the timestamp is almost useless because instruction before and after it can get reordered in cpu.

**Comment by MengRao** [comment]
changed to using **rdtscp**, so cpu reordering is prevented.
